#!/usr/bin/env bash
# embed-pane battery — the PANE RUNTIME as it ships (templates/center/shell/assets/, D-045).
#
# The seven runtime files are GENERATED by docs/design/embed-graph/promote.py; tests/gabe-universe 11c
# proves they are a fresh extract. This battery proves what they must DO once shipped:
#   STATIC (always runs, every assert with a sed FIRE on a temp copy): the seven files are there and
#     say GENERATED · GabePane.destroy is on the public surface · pane.render starts with the dead-pane
#     guard · the console skin wraps destroy · the scoped _pane.css carries no page-wide rule and every
#     selector sits under `.seat ` · no runtime file carries a machine path or a line-number citation ·
#     a FIRE counts only when the check fails for its own reason (a checker that crashes is not a fire).
#   HEADLESS (a real browser, tests/embed-pane/destroy.mjs over harness.html): the destroy contract —
#     context lost (even when the dispose throws), canvases gone, nothing redraws after — and its FIRE:
#     a no-op destroy turns the canvas and context asserts red.
#   SEATS (a real browser, tests/embed-pane/seats.mjs over BUILT centres): the board's two seats and its
#     done-card sha chips on seatfix.py projects — git history at core.abbrev 8 and at 7, the plain project
#     (no git: honest-empty), a copy without assets/3d-bundle.js (the seat names it), a copy whose commits.js
#     is the empty stub beside a populated LEDGER, a copy whose picker is capped below the feed (a chip past
#     it) — and its FIRE: one mutated copy per assert, all in ONE browser pass, each turning ITS assert red (a
#     join on `short` · a substring join · the oldest preselected · the undrawable wording lost · the head
#     never restored · the seats folded · a failed embed marked drawn · a spine head that invites a pick
#     nothing can draw · no boot · the empty guard dropped · empty columns vanishing · the spine bailing with
#     the runtime · a chip joined by its first sha only · a chip click that never draws · a chip click that
#     reaches the card · a chip past the picker called 'not in the feed' · the chips run where no cap bites).
# No chrome or no Playwright is RED, not a skip: a checker that cannot run is not evidence (O14).
# Exit 0 = all pass.
set -u
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
ASSETS="$REPO/templates/center/shell/assets"
HERE="$REPO/tests/embed-pane"
FILES="_grammar.js _slice.js _uni-grammar.js _pane.js _pane-console.js _pane.css _pane-console.css"

T=$(mktemp -d)
trap 'rm -rf "$T"' EXIT
pass=0; fail=0
ok()  { pass=$((pass+1)); }
bad() { fail=$((fail+1)); echo "  FAIL: $1"; }

# static <assets dir> <check> — exit 0 when the check holds on the runtime files in that dir
static() {
  python3 - "$1" "$2" "$FILES" <<'PY'
import re, sys, pathlib
d, check, files = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3].split()
def read(n): return (d / n).read_text(encoding="utf-8")
def fail(msg): print("    " + msg); sys.exit(3)     # 3 = the check failed; a traceback exits 1 and is NOT a fire
if check == "files":
    missing = [n for n in files if not (d / n).is_file()]
    missing and fail("missing from assets/: " + ", ".join(missing))
elif check == "generated":
    bare = [n for n in files if "GENERATED by docs/design/embed-graph/promote.py" not in "\n".join(read(n).split("\n")[:8])]
    bare and fail("no GENERATED header (hand-copied?): " + ", ".join(bare))
elif check == "surface":
    m = re.search(r"\n  return \{ mount: mount,.*?\};\n\}\)\(\);\s*$", read("_pane.js"), re.S)
    (m and re.search(r"\bdestroy: function \(p\) \{ if \(p && p\.destroy\) p\.destroy\(\); \}", m.group(0))) \
        or fail("GabePane.destroy is not on the public surface")
elif check == "guard":
    re.search(r"pane\.render = function \(\) \{\n\s*if \(pane\.__dead\) return;\n", read("_pane.js")) \
        or fail("pane.render does not open with the dead-pane guard")
elif check == "console":
    re.search(r"var d0 = pane\.destroy;\n\s*pane\.destroy = function \(\) \{ if \(TIP\) TIP\.classList\.remove\(\"on\"\); d0\(\); \};",
              read("_pane-console.js")) or fail("the console skin does not wrap destroy (the body tip would stay lit)")
elif check == "css":
    css = re.sub(r"/\*.*?\*/", "", read("_pane.css"), flags=re.S)
    i, bad = 0, []
    while True:
        j = css.find("{", i)
        if j < 0: break
        for sel in (s.strip() for s in css[i:j].split(",")):
            if sel in (":root", "body", "html", "*", "a") or not sel.startswith(".seat "): bad.append(sel)
        k = css.find("}", j)
        if k < 0: fail("unbalanced rule after " + css[i:j].strip()[:60])
        i = k + 1
    bad and fail("rules outside .seat in _pane.css: " + ", ".join(bad[:6]))
elif check == "paths":
    hits = [n for n in files if "/home/" in read(n) or "file:///" in read(n)]
    hits and fail("a machine path in: " + ", ".join(hits))
elif check == "cites":
    # a line number rots on the next edit of the file it points at, and a byte copy ships the rot to every
    # centre: cite the symbol (`var LZ=`, `_hlCompute`), never the line. _uni-grammar.js is exempt: its band
    # text is the station's own words, and 11c proves the tool's header carries no line number.
    rx = re.compile(r"\.(?:html|js|mjs|py|css|md)\s?:\d{2,5}\b|(?:^|[\s(`'\"-]):\d{2,5}\b", re.M)
    hits = [n + ":" + str(read(n)[:m.start()].count("\n") + 1)
            for n in files if n != "_uni-grammar.js" for m in rx.finditer(read(n))]
    hits and fail("a line-number citation in: " + ", ".join(hits[:6]) + " — cite the symbol, not the line")
PY
}
fresh() { rm -rf "$T/a"; mkdir -p "$T/a"; for f in $FILES; do cp "$ASSETS/$f" "$T/a/"; done; }
# fired <check> <expect> — the check failed on the mutant in $T/a FOR ITS OWN REASON: exit 3 and its own
# message. A checker that dies on the mutant (a traceback exits 1) is not a check that fired.
fired() { static "$T/a" "$1" >"$T/fire.out" 2>&1; [ $? = 3 ] && grep -qF -- "$2" "$T/fire.out"; }
fire() {   # fire <check> <label> <expect>
  fired "$1" "$3" && ok || { bad "FIRE $2: the '$1' check did not fail for its own reason on the mutant"; tail -3 "$T/fire.out"; }
}

# ── STATIC · SILENT: the shipped files pass every check ──
for c in files generated surface guard console css paths cites; do
  static "$ASSETS" "$c" && ok || bad "static '$c' on the shipped assets"
done

# ── STATIC · FIRE: each check goes red on its mutant ──
fresh; rm "$T/a/_slice.js";                                                    fire files "a runtime file missing" "missing from assets/: _slice.js"
fresh; sed -i 's/GENERATED by/generated by/' "$T/a/_pane.js";                   fire generated "a hand copy without the header" "no GENERATED header"
fresh; sed -i 's/destroy: function (p)/destroyed: function (p)/' "$T/a/_pane.js"; fire surface "destroy off the surface" "GabePane.destroy is not on the public surface"
fresh; sed -i '/pane.render = function () {/{n;d}' "$T/a/_pane.js";              fire guard "the dead-pane guard deleted" "does not open with the dead-pane guard"
fresh; sed -i 's/pane.destroy = function () { if (TIP)/pane.destroyed = function () { if (TIP)/' "$T/a/_pane-console.js"; fire console "the console wrapper unhooked" "does not wrap destroy"
for rule in ':root { --x: 1; }' 'body { margin: 0; }' '* { box-sizing: border-box; }' 'a { color: red; }' '.pn-x { color: red; }' '.seat .pn, .pnc { color: red; }'; do
  fresh; printf '%s\n' "$rule" >>"$T/a/_pane.css";                             fire css "unscoped rule: $rule" "rules outside .seat in _pane.css"
done
fresh; printf '/* /home/someone/x */\n' >>"$T/a/_slice.js";                     fire paths "a /home/ path" "a machine path in: _slice.js"
fresh; printf '/* file:///x */\n' >>"$T/a/_pane.css";                           fire paths "a file:/// url" "a machine path in: _pane.css"
fresh; printf '/* the ground (gabe-universe.html :5444) */\n' >>"$T/a/_pane.js"; fire cites "a spaced line citation" "a line-number citation in: _pane.js"
fresh; printf '/* its rule at gabe-universe.html:1356-1359 */\n' >>"$T/a/_slice.js"; fire cites "a joined line range" "a line-number citation in: _slice.js"
# SILENT on code that only looks like one: an object literal's key:number and a clock time are not citations
fresh; printf 'var LZ2 = { api:150, web:-60 }; var at = "12:30"; /* see `var LZ=` */\n' >>"$T/a/_pane.js"
static "$T/a" cites >"$T/fire.out" 2>&1 && ok || { bad "SILENT cites: a key:number literal read as a line citation"; cat "$T/fire.out"; }
# the helper's own FIRE: a mutant the checker DIES on (no _pane.js to read) is not a check that fired
fresh; rm "$T/a/_pane.js"
fired surface "GabePane.destroy is not on the public surface" && bad "FIRE helper: a checker that crashed was read as a fire" || ok
echo "  static: $pass passed, $fail failed"

# ── HEADLESS: the destroy contract in a real browser ──
CHROME="${GABE_CHROME_BIN:-/usr/bin/google-chrome-stable}"
[ -n "${GABE_PW_DIR:-}" ] && [ -z "${PLAYWRIGHT_DIR:-}" ] && export PLAYWRIGHT_DIR="$GABE_PW_DIR"
PW=0; node --input-type=module -e "await import('$REPO/skills/gabe-docsite/tools/_playwright.mjs')" >/dev/null 2>&1 && PW=1
if [ -x "$CHROME" ] && [ "$PW" = 1 ]; then
  export GABE_CHROME_BIN="$CHROME"
  timeout 240 node "$HERE/destroy.mjs" "$HERE/harness.html" >"$T/live.out" 2>&1; RC=$?
  cat "$T/live.out"
  [ "$RC" = 0 ] && ok || bad "headless: the destroy contract failed on the shipped runtime (rc $RC)"
  # FIRE: the same harness, staged over a runtime whose destroy is a no-op
  ST="$T/stage"; mkdir -p "$ST/tests/embed-pane" "$ST/templates/center/shell/assets"
  cp "$HERE/harness.html" "$ST/tests/embed-pane/"
  for f in $FILES 3d-bundle.js; do ln -s "$ASSETS/$f" "$ST/templates/center/shell/assets/$f"; done
  ln -s "$REPO/templates/center/shell/example" "$ST/templates/center/shell/example"
  rm "$ST/templates/center/shell/assets/_pane.js"
  sed 's/^    pane\.destroy = function () {$/    pane.destroy = function () { return;/' "$ASSETS/_pane.js" >"$ST/templates/center/shell/assets/_pane.js"
  grep -q 'pane.destroy = function () { return;' "$ST/templates/center/shell/assets/_pane.js" \
    && ok || bad "fixture: the no-op destroy mutation did not apply"
  timeout 240 node "$HERE/destroy.mjs" "$ST/tests/embed-pane/harness.html" >"$T/fire.out" 2>&1; RC=$?
  if [ "$RC" != 0 ] && grep -q 'FAIL  D2' "$T/fire.out" && grep -q 'FAIL  D3' "$T/fire.out" && grep -q 'FAIL  D8' "$T/fire.out"; then ok
  else bad "headless FIRE: a no-op destroy must turn D2 (canvases), D3 and D8 (context lost) red (rc $RC)"; cat "$T/fire.out"; fi
  echo "  headless FIRE (no-op destroy): $(grep -c '  FAIL  ' "$T/fire.out") case(s) red — $(grep -o 'FAIL  D[0-9]' "$T/fire.out" | cut -c7- | tr '\n' ' ')"

  # ── SEATS: the board's two seats on built centres (one browser, the pages in turn) ──
  GEN="$REPO/templates/center/generators"
  seatbuild() {   # seatbuild <name> <seatfix.py flags…> → a built centre at $T/<name>/docs/site/center
    mkdir -p "$T/$1" && python3 "$HERE/seatfix.py" "$T/$1" "${@:2}" >/dev/null \
      && (cd "$T" && GABE_REPO_ROOT="$T/$1" GABE_SHELL_SRC="$REPO/templates/center/shell" GABE_GRAFT_BUILD=0 \
            python3 "$GEN/build_center_a3.py" >"$T/$1.build.out" 2>&1)
  }
  if seatbuild sf8 --project --history --abbrev 8 && seatbuild sf7 --project --history --abbrev 7 && seatbuild plain --project; then
    ok
    SF8="$T/sf8/docs/site/center"
    cp -r "$SF8" "$T/nobundle"; rm "$T/nobundle/assets/3d-bundle.js"
    cp -r "$SF8" "$T/stub"; cp "$T/plain/docs/site/center/commits.js" "$T/stub/commits.js"   # the honest-empty stub, the LEDGER kept
    # the picker capped below the feed (3 commits): the chip naming the OLDEST commit sits in the feed, past the picker
    cp -r "$SF8" "$T/capped"; sed -i -E 's/ data-cap="[0-9]+"/ data-cap="2"/' "$T/capped/board.html"
    grep -q ' data-cap="2"' "$T/capped/board.html" && ok || bad "fixture: the capped copy's data-cap did not apply"
    timeout 300 node "$HERE/seats.mjs" full="$SF8/board.html" full="$T/sf7/docs/site/center/board.html" \
      empty="$T/plain/docs/site/center/board.html" missing="$T/nobundle/board.html" stub="$T/stub/board.html" \
      chips="$T/capped/board.html" >"$T/seats.out" 2>&1; RC=$?
    cat "$T/seats.out"
    [ "$RC" = 0 ] && ok || bad "seats: the board's seats failed on the built fixtures (rc $RC)"

    # FIRE — one mutated copy per assert (never the source), all in one browser pass: each must turn ITS assert red
    mutant() {   # mutant <tag> <base centre> <file in the copy> <old> <new> [<old> <new> …] — exact replacements, each once
      rm -rf "$T/m-$1"; cp -r "$2" "$T/m-$1"
      python3 - "$T/m-$1/$3" "${@:4}" <<'PY' || bad "fixture: the $1 mutation did not apply"
import sys
f, pairs = sys.argv[1], sys.argv[2:]
s = open(f, encoding="utf-8").read()
for old, new in zip(pairs[::2], pairs[1::2]):
    if s.count(old) != 1: sys.exit(1)
    s = s.replace(old, new)
open(f, "w", encoding="utf-8").write(s)
PY
    }
    PLAIN="$T/plain/docs/site/center"; HP_OLD='(live && !missing.length ? live + " drawable — pick a ● to draw it below" : "none drawable — " + why)'
    mutant exact    "$SF8" assets/seats.js 'if (String(C[i].sha || "").toLowerCase().lastIndexOf(s, 0) !== 0) continue;' 'if (String(C[i].short || "").toLowerCase() !== s) continue;'
    mutant substr   "$SF8" assets/seats.js '.toLowerCase().lastIndexOf(s, 0) !== 0) continue;' '.toLowerCase().indexOf(s) < 0) continue;'
    mutant oldest   "$SF8" assets/seats.js '      pick(0, false);' '      pick(rows.length - 1, false);'
    mutant wording  "$SF8" assets/seats.js '"in the feed" : "not in the feed";' '"in the feed" : "the feed stops";'
    mutant nohead   "$SF8" assets/seats.js $'    function show(i) {\n      say(host, base);\n' $'    function show(i) {\n'
    mutant fold     "$SF8" assets/a3.css '.desc-min .kpis{display:none}' '.desc-min .kpis{display:none} .desc-min .seats{display:none}'
    mutant noretry  "$SF8" assets/seats.js 'cur = null; at = -1; row.innerHTML = ""; host.removeAttribute("data-picked");' \
                                           'cur = null; at = i; row.innerHTML = ""; host.setAttribute("data-picked", cs[i].short);' \
                                           $'        cur = null; at = -1; host.removeAttribute("data-picked");\n' ''
    mutant headpick "$SF8" assets/seats.js "$HP_OLD" '"pick one to draw it below"'
    mutant hpmiss   "$T/nobundle" assets/seats.js "$HP_OLD" '"pick one to draw it below"'
    mutant hpstub   "$T/stub" assets/seats.js "$HP_OLD" '"pick one to draw it below"'
    mutant noboot   "$PLAIN" assets/seats.js $'(function () {\n  var W = window;' $'(function () { return;\n  var W = window;'
    mutant noguard  "$PLAIN" assets/seats.js '    if (!cs.length) {' '    if (false) {'
    mutant vanish   "$PLAIN" assets/seats.js '    order.forEach(function (beat) {' '    order.filter(function (b) { return (S.beats[b] || []).length; }).forEach(function (beat) {'
    mutant bail     "$T/nobundle" assets/seats.js '  if (sp) boot(sp, spine);' '  if (sp && !missing.length) boot(sp, spine);'
    mutant chipone  "$SF8" assets/seats.js 'var k = pickOf({ sha: shas[0], shas: shas });' 'var k = pickOf({ sha: shas[0], shas: [shas[0]] });'
    mutant chipdead "$SF8" assets/seats.js '        if (k >= 0) toChanges(k, shas[0], "done card");' ''
    mutant chipleak "$SF8" assets/seats.js '        ev.stopPropagation();' ''
    mutant pastlie  "$T/capped" assets/seats.js '(k < 0 ? (fed ? " — in the feed, past the "' '(k < 0 ? (false ? " — in the feed, past the "'
    timeout 900 node "$HERE/seats.mjs" full@exact="$T/m-exact/board.html" full@substr="$T/m-substr/board.html" \
      full@oldest="$T/m-oldest/board.html" full@wording="$T/m-wording/board.html" full@nohead="$T/m-nohead/board.html" \
      full@fold="$T/m-fold/board.html" full@noretry="$T/m-noretry/board.html" full@headpick="$T/m-headpick/board.html" \
      missing@hpmiss="$T/m-hpmiss/board.html" stub@hpstub="$T/m-hpstub/board.html" empty@noboot="$T/m-noboot/board.html" \
      empty@noguard="$T/m-noguard/board.html" empty@vanish="$T/m-vanish/board.html" missing@bail="$T/m-bail/board.html" \
      full@chipone="$T/m-chipone/board.html" full@chipdead="$T/m-chipdead/board.html" full@chipleak="$T/m-chipleak/board.html" \
      chips@pastlie="$T/m-pastlie/board.html" chips@uncapped="$SF8/board.html" \
      >"$T/seats-fire.out" 2>&1; RC=$?
    fired() {    # fired <run> <assert prefix> <what the mutant did> — that run's assert is red
      grep -qF "  FAIL  $1 $2" "$T/seats-fire.out" && ok || bad "seats FIRE ($1): $3 must turn '$2' red"
    }
    [ "$RC" != 0 ] && ok || bad "seats FIRE: the mutated copies must fail the run (rc $RC)"
    fired full@exact    "S5 a ledger token of another length"          "a join on \`short\`"
    grep -qF '  PASS  full@exact S2' "$T/seats-fire.out" && ok || bad "seats FIRE (full@exact): the page must still boot and draw — S5 red for its own reason"
    fired full@substr   "S5 every spine ●/○ equals the prefix join"     "a SUBSTRING join (the inner-piece token lit)"
    fired full@oldest   "S4 the spine holds GABE_SPINE.order"           "the oldest entry preselected"
    fired full@wording  "S6 an undrawable spine pick"                   "the 'not in the feed' wording lost"
    fired full@nohead   "S6 the changes picker restores its own head"   "a show() that never restores its head"
    fired full@fold     "S7 folding the intro"                          "the seats folded with the intro"
    fired full@noretry  "S8 an embed that throws"                       "a failed embed recorded as drawn"
    fired full@noretry  "S8 picking the same commit again"              "a failed embed recorded as drawn"
    fired full@headpick "S5 the spine head counts the drawable"         "a spine head that never counts"
    fired missing@hpmiss "M3 the spine head says none is drawable"      "a spine head inviting a pick the runtime cannot draw"
    fired stub@hpstub   "T2 the spine lists every entry"                "a spine head inviting a pick commits.js cannot draw"
    fired empty@noboot  "S0 the seats booted"                           "a seats.js that never boots"
    fired empty@noguard "E1 \"commits.js carries no commits\""          "the empty guard dropped"
    fired empty@vanish  "E2 the spine keeps its five columns"           "empty columns vanishing"
    fired missing@bail  "M2 the spine still renders every beat"         "a spine that bails with the runtime"
    fired full@chipone  "S9 every done-card chip"                       "a chip joined by its first sha only"
    fired full@chipdead "S9 a click on a ● chip"                        "a chip click that never draws"
    fired full@chipleak "S9 a click on a ● chip"                        "a chip click that reaches the card"
    fired full@chipleak "S9 a click on a ○ chip"                        "a chip click that reaches the card"
    fired chips@pastlie "S9 every done-card chip"                       "a ○ past the picker's cap called 'not in the feed'"
    fired chips@uncapped "S9 a chip whose commit the feed carries past" "the chips run on a copy the cap does not bite"
    echo "  seats FIRE (one pass, $(grep -c '  ── ' "$T/seats-fire.out") mutated copies): $(grep -c '  FAIL  ' "$T/seats-fire.out") case(s) red — $(grep -o 'FAIL  [a-z]*@[a-z]* [A-Z][0-9]' "$T/seats-fire.out" | cut -c7- | sort -u | tr '\n' ' ')"
  else
    bad "seats: a seat fixture did not build"; tail -5 "$T"/*.build.out
  fi
else
  bad "headless: RED — the destroy contract and the seats DID NOT RUN (chrome at $CHROME: $([ -x "$CHROME" ] && echo yes || echo no) · playwright: $([ "$PW" = 1 ] && echo yes || echo no))"
  echo "         provision: a system chrome (or GABE_CHROME_BIN) + playwright: mkdir -p docs/design/graft-adoption/spike/_build && (cd \$_ && npm i playwright-core), then GABE_PW_DIR=<that>/node_modules/playwright-core (see tests/gabe-universe/run.sh)"
fi

[ "$fail" = 0 ] && { echo "embed-pane battery: ALL PASS ($pass)"; exit 0; }
echo "embed-pane battery: $fail FAILED, $pass passed"; exit 1
