#!/usr/bin/env bash
# embed-pane battery — the PANE RUNTIME as it ships (templates/center/shell/assets/, D-045).
#
# The seven runtime files are GENERATED by docs/design/embed-graph/promote.py; tests/gabe-universe 11c
# proves they are a fresh extract. This battery proves what they must DO once shipped:
#   STATIC (always runs, every assert with a sed FIRE on a temp copy): the seven files are there and
#     say GENERATED · GabePane.destroy is on the public surface · pane.render starts with the dead-pane
#     guard · the console skin wraps destroy · the scoped _pane.css carries no page-wide rule and every
#     selector sits under `.seat ` · no runtime file carries a machine path or a line-number citation ·
#     a FIRE counts only when the check fails for its own reason (a checker that crashes is not a fire).
#   HEADLESS (a real browser, tests/embed-pane/destroy.mjs over harness.html): the destroy contract —
#     context lost (even when the dispose throws), canvases gone, nothing redraws after — and its FIRE:
#     a no-op destroy turns the canvas and context asserts red.
# No chrome or no Playwright is RED, not a skip: a checker that cannot run is not evidence (O14).
# Exit 0 = all pass.
set -u
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
ASSETS="$REPO/templates/center/shell/assets"
HERE="$REPO/tests/embed-pane"
FILES="_grammar.js _slice.js _uni-grammar.js _pane.js _pane-console.js _pane.css _pane-console.css"

T=$(mktemp -d)
trap 'rm -rf "$T"' EXIT
pass=0; fail=0
ok()  { pass=$((pass+1)); }
bad() { fail=$((fail+1)); echo "  FAIL: $1"; }

# static <assets dir> <check> — exit 0 when the check holds on the runtime files in that dir
static() {
  python3 - "$1" "$2" "$FILES" <<'PY'
import re, sys, pathlib
d, check, files = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3].split()
def read(n): return (d / n).read_text(encoding="utf-8")
def fail(msg): print("    " + msg); sys.exit(3)     # 3 = the check failed; a traceback exits 1 and is NOT a fire
if check == "files":
    missing = [n for n in files if not (d / n).is_file()]
    missing and fail("missing from assets/: " + ", ".join(missing))
elif check == "generated":
    bare = [n for n in files if "GENERATED by docs/design/embed-graph/promote.py" not in "\n".join(read(n).split("\n")[:8])]
    bare and fail("no GENERATED header (hand-copied?): " + ", ".join(bare))
elif check == "surface":
    m = re.search(r"\n  return \{ mount: mount,.*?\};\n\}\)\(\);\s*$", read("_pane.js"), re.S)
    (m and re.search(r"\bdestroy: function \(p\) \{ if \(p && p\.destroy\) p\.destroy\(\); \}", m.group(0))) \
        or fail("GabePane.destroy is not on the public surface")
elif check == "guard":
    re.search(r"pane\.render = function \(\) \{\n\s*if \(pane\.__dead\) return;\n", read("_pane.js")) \
        or fail("pane.render does not open with the dead-pane guard")
elif check == "console":
    re.search(r"var d0 = pane\.destroy;\n\s*pane\.destroy = function \(\) \{ if \(TIP\) TIP\.classList\.remove\(\"on\"\); d0\(\); \};",
              read("_pane-console.js")) or fail("the console skin does not wrap destroy (the body tip would stay lit)")
elif check == "css":
    css = re.sub(r"/\*.*?\*/", "", read("_pane.css"), flags=re.S)
    i, bad = 0, []
    while True:
        j = css.find("{", i)
        if j < 0: break
        for sel in (s.strip() for s in css[i:j].split(",")):
            if sel in (":root", "body", "html", "*", "a") or not sel.startswith(".seat "): bad.append(sel)
        k = css.find("}", j)
        if k < 0: fail("unbalanced rule after " + css[i:j].strip()[:60])
        i = k + 1
    bad and fail("rules outside .seat in _pane.css: " + ", ".join(bad[:6]))
elif check == "paths":
    hits = [n for n in files if "/home/" in read(n) or "file:///" in read(n)]
    hits and fail("a machine path in: " + ", ".join(hits))
elif check == "cites":
    # a line number rots on the next edit of the file it points at, and a byte copy ships the rot to every
    # centre: cite the symbol (`var LZ=`, `_hlCompute`), never the line. _uni-grammar.js is exempt: its band
    # text is the station's own words, and 11c proves the tool's header carries no line number.
    rx = re.compile(r"\.(?:html|js|mjs|py|css|md)\s?:\d{2,5}\b|(?:^|[\s(`'\"-]):\d{2,5}\b", re.M)
    hits = [n + ":" + str(read(n)[:m.start()].count("\n") + 1)
            for n in files if n != "_uni-grammar.js" for m in rx.finditer(read(n))]
    hits and fail("a line-number citation in: " + ", ".join(hits[:6]) + " — cite the symbol, not the line")
PY
}
fresh() { rm -rf "$T/a"; mkdir -p "$T/a"; for f in $FILES; do cp "$ASSETS/$f" "$T/a/"; done; }
# fired <check> <expect> — the check failed on the mutant in $T/a FOR ITS OWN REASON: exit 3 and its own
# message. A checker that dies on the mutant (a traceback exits 1) is not a check that fired.
fired() { static "$T/a" "$1" >"$T/fire.out" 2>&1; [ $? = 3 ] && grep -qF -- "$2" "$T/fire.out"; }
fire() {   # fire <check> <label> <expect>
  fired "$1" "$3" && ok || { bad "FIRE $2: the '$1' check did not fail for its own reason on the mutant"; tail -3 "$T/fire.out"; }
}

# ── STATIC · SILENT: the shipped files pass every check ──
for c in files generated surface guard console css paths cites; do
  static "$ASSETS" "$c" && ok || bad "static '$c' on the shipped assets"
done

# ── STATIC · FIRE: each check goes red on its mutant ──
fresh; rm "$T/a/_slice.js";                                                    fire files "a runtime file missing" "missing from assets/: _slice.js"
fresh; sed -i 's/GENERATED by/generated by/' "$T/a/_pane.js";                   fire generated "a hand copy without the header" "no GENERATED header"
fresh; sed -i 's/destroy: function (p)/destroyed: function (p)/' "$T/a/_pane.js"; fire surface "destroy off the surface" "GabePane.destroy is not on the public surface"
fresh; sed -i '/pane.render = function () {/{n;d}' "$T/a/_pane.js";              fire guard "the dead-pane guard deleted" "does not open with the dead-pane guard"
fresh; sed -i 's/pane.destroy = function () { if (TIP)/pane.destroyed = function () { if (TIP)/' "$T/a/_pane-console.js"; fire console "the console wrapper unhooked" "does not wrap destroy"
for rule in ':root { --x: 1; }' 'body { margin: 0; }' '* { box-sizing: border-box; }' 'a { color: red; }' '.pn-x { color: red; }' '.seat .pn, .pnc { color: red; }'; do
  fresh; printf '%s\n' "$rule" >>"$T/a/_pane.css";                             fire css "unscoped rule: $rule" "rules outside .seat in _pane.css"
done
fresh; printf '/* /home/someone/x */\n' >>"$T/a/_slice.js";                     fire paths "a /home/ path" "a machine path in: _slice.js"
fresh; printf '/* file:///x */\n' >>"$T/a/_pane.css";                           fire paths "a file:/// url" "a machine path in: _pane.css"
fresh; printf '/* the ground (gabe-universe.html :5444) */\n' >>"$T/a/_pane.js"; fire cites "a spaced line citation" "a line-number citation in: _pane.js"
fresh; printf '/* its rule at gabe-universe.html:1356-1359 */\n' >>"$T/a/_slice.js"; fire cites "a joined line range" "a line-number citation in: _slice.js"
# SILENT on code that only looks like one: an object literal's key:number and a clock time are not citations
fresh; printf 'var LZ2 = { api:150, web:-60 }; var at = "12:30"; /* see `var LZ=` */\n' >>"$T/a/_pane.js"
static "$T/a" cites >"$T/fire.out" 2>&1 && ok || { bad "SILENT cites: a key:number literal read as a line citation"; cat "$T/fire.out"; }
# the helper's own FIRE: a mutant the checker DIES on (no _pane.js to read) is not a check that fired
fresh; rm "$T/a/_pane.js"
fired surface "GabePane.destroy is not on the public surface" && bad "FIRE helper: a checker that crashed was read as a fire" || ok
echo "  static: $pass passed, $fail failed"

# ── HEADLESS: the destroy contract in a real browser ──
CHROME="${GABE_CHROME_BIN:-/usr/bin/google-chrome-stable}"
[ -n "${GABE_PW_DIR:-}" ] && [ -z "${PLAYWRIGHT_DIR:-}" ] && export PLAYWRIGHT_DIR="$GABE_PW_DIR"
PW=0; node --input-type=module -e "await import('$REPO/skills/gabe-docsite/tools/_playwright.mjs')" >/dev/null 2>&1 && PW=1
if [ -x "$CHROME" ] && [ "$PW" = 1 ]; then
  export GABE_CHROME_BIN="$CHROME"
  timeout 240 node "$HERE/destroy.mjs" "$HERE/harness.html" >"$T/live.out" 2>&1; RC=$?
  cat "$T/live.out"
  [ "$RC" = 0 ] && ok || bad "headless: the destroy contract failed on the shipped runtime (rc $RC)"
  # FIRE: the same harness, staged over a runtime whose destroy is a no-op
  ST="$T/stage"; mkdir -p "$ST/tests/embed-pane" "$ST/templates/center/shell/assets"
  cp "$HERE/harness.html" "$ST/tests/embed-pane/"
  for f in $FILES 3d-bundle.js; do ln -s "$ASSETS/$f" "$ST/templates/center/shell/assets/$f"; done
  ln -s "$REPO/templates/center/shell/example" "$ST/templates/center/shell/example"
  rm "$ST/templates/center/shell/assets/_pane.js"
  sed 's/^    pane\.destroy = function () {$/    pane.destroy = function () { return;/' "$ASSETS/_pane.js" >"$ST/templates/center/shell/assets/_pane.js"
  grep -q 'pane.destroy = function () { return;' "$ST/templates/center/shell/assets/_pane.js" \
    && ok || bad "fixture: the no-op destroy mutation did not apply"
  timeout 240 node "$HERE/destroy.mjs" "$ST/tests/embed-pane/harness.html" >"$T/fire.out" 2>&1; RC=$?
  if [ "$RC" != 0 ] && grep -q 'FAIL  D2' "$T/fire.out" && grep -q 'FAIL  D3' "$T/fire.out" && grep -q 'FAIL  D8' "$T/fire.out"; then ok
  else bad "headless FIRE: a no-op destroy must turn D2 (canvases), D3 and D8 (context lost) red (rc $RC)"; cat "$T/fire.out"; fi
  echo "  headless FIRE (no-op destroy): $(grep -c '  FAIL  ' "$T/fire.out") case(s) red — $(grep -o 'FAIL  D[0-9]' "$T/fire.out" | cut -c7- | tr '\n' ' ')"
else
  bad "headless: RED — the destroy contract DID NOT RUN (chrome at $CHROME: $([ -x "$CHROME" ] && echo yes || echo no) · playwright: $([ "$PW" = 1 ] && echo yes || echo no))"
  echo "         provision: a system chrome (or GABE_CHROME_BIN) + playwright: mkdir -p docs/design/graft-adoption/spike/_build && (cd \$_ && npm i playwright-core), then GABE_PW_DIR=<that>/node_modules/playwright-core (see tests/gabe-universe/run.sh)"
fi

[ "$fail" = 0 ] && { echo "embed-pane battery: ALL PASS ($pass)"; exit 0; }
echo "embed-pane battery: $fail FAILED, $pass passed"; exit 1
